require 'spec_helper'

describe 'base::yum::clean' do

  it { is_expected.to compile }

  let(:facts) {{ :fqdn => 'example.unrulymedia.com' }}

  it { is_expected.to contain_cron('clean_yum_cache_from_nagios_security_check').with(
    :user    => 'root',
    :command => "su - nagios -s /bin/bash  -c '/usr/bin/yum clean all' 2>&1 | logger -i -t yum-clean",
    :minute  => '12', # generated by fqdn_rand (0.60) on fqdn example.unrulymedia.com
    :hour    => '17', # generated by fqdn_rand (0,24) on fqdn example.unrulymedia.com
  ) }
end
